### ISSUE TITLE
confluent start not starting control-center

### ISSUE THREAD

**Issue by ayush-chauhan** [confluentinc/confluent-cli#105]
I have downloaded Confluent 5.0.0 open source and following the quickstart guide to explore confluent. When I ran bin/confluent start it gives the following output 
```
Starting zookeeper
zookeeper is [UP]
Starting kafka
kafka is [UP]
Starting schema-registry
schema-registry is [UP]
Starting kafka-rest
kafka-rest is [UP]
Starting connect
connect is [UP]
Starting ksql-server
ksql-server is [UP]
```

Whereas in the [documentation](https://docs.confluent.io/current/quickstart/cos-quickstart.html#step-1-download-and-install), it also starts control-center. 

I even tried to start control-center manually(`bin/confluent control-center`) but got this error `Unknown command 'control-center'`

I think due to this, whenever I try to add sample data for the Kafka topic I am getting `java.lang.ClassNotFoundException: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor`

**Comment by ewencp** [comment]
Control Center is part of the Confluent Enterprise offering. It is not included in Confluent Open Source.

**Comment by ayush-chauhan** [comment]
Yeah, I see that. In the documentation, all the commands are given for enterprise edition and nothing is mentioned about it.

**Comment by JimGalasyn** [comment]
@ayush-chauhan, thanks for the heads up! This is issue has been fixed in the topic.

**Comment by ayush-chauhan** [comment]
@JimGalasyn Thanks for updating it
