### ISSUE TITLE
Schema Registry failed to start with confluence version 5.0.0

### ISSUE THREAD

**Issue by rahulbhanushali** [confluentinc/confluent-cli#106]
I'm trying to run the confluent OSS platform locally following the instructions as described here: https://docs.confluent.io/current/quickstart/cos-quickstart.html#cos-quickstart

However on executing  `bin/confluent start` schema registry fails to start. Here's the output of the command:
```confluent-5.0.0 bin/confluent start
current dir: /var/folders/c8/q06dsl7s3jz0lqc6xvcpnqnm0000gp/T/
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT:
zookeeper is already running. Try restarting if needed
Starting kafka
kafka is [UP]
Starting schema-registry
\Schema Registry failed to start
schema-registry is [DOWN]
Cannot start Kafka Rest, Kafka Server is not running. Check your deployment
```

**Logs of the schema registry are as below:**

```ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
io.confluent.common.config.ConfigException: No supported Kafka endpoints are configured. Either kafkastore.bootstrap.servers must have at least one endpoint matching kafkastore.security.protocol or broker endpoints loaded from ZooKeeper must have at least one endpoint matching kafkastore.security.protocol.
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.endpointsToBootstrapServers(SchemaRegistryConfig.java:630)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig.bootstrapBrokers(SchemaRegistryConfig.java:570)
	at io.confluent.kafka.schemaregistry.storage.KafkaStore.<init>(KafkaStore.java:101)
	at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.<init>(KafkaSchemaRegistry.java:139)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:59)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:41)
	at io.confluent.rest.Application.createServer(Application.java:169)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:43)
```

Looking at the SchemaRegistry values displayed in the logs. Looks like the issue is with the 
 `kafkastore.bootstrap.servers = []` setting.

**Comment by rahulbhanushali** [comment]
The issue was with the `etc/schema-registry/schema-registry.properties` file.
The line `kafkastore.bootstrap.servers=PLAINTEXT://localhost:9092` was commented.

**Comment by cricket007** [comment]
Looks like you already had zookeeper running. 

But the issue can also be solved with this condition

> broker endpoints loaded from ZooKeeper must have at least one endpoint matching kafkastore.security.protocol

**Comment by rahulbhanushali** [comment]
I doubt on that, from what I recall there was no zookeeper running. Also, I had tried the same setup on another machine and was facing the same problem.

However, the issue seems to have been resolved in the latest tar. Hence closing this.

**Comment by kemathur** [comment]
Same issue

**Comment by cricket007** [comment]
@kemathur  You're going to have to be more specific.

For example, the more information the better, e.g. OS version, Java version, Confluent & Kafka version. Property files. Commands used. Logs.

Please open a new issue including all of the above

**Comment by lucasscottiks** [comment]
Using CONFLUENT_CURRENT: /tmp/confluent.9YQRvpqd

For me helped just remove this file "confluent.9YQRvpqd"

for now

**Comment by alecsolter** [comment]
@lucasscottiks by removing this directory you will lose all the topics you've created through the Control Center. There should be another way...

**Comment by punitgupta87** [comment]
I killed the processes , properly stopped ksql servert , kafka and stopped zookeeper but after all this when I try to restart ksql server I get the same error. I can delete all the data by : rm -rf /tmp/conf* but this will delete all the data and topics , please help
