### ISSUE TITLE
How do I configure JMX_PORT for the broker?

### ISSUE THREAD

**Issue by russau** [confluentinc/confluent-cli#114]
When I set `JMX_PORT` as an environment variable, I see a failure as zookeeper is using the same setting.

``` bash
$ export JMX_PORT=9990
$ confluent start kafka
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /var/folders/gj/gkgkr_p141s0r7w1wbs2zzlr0000gn/T/confluent.Msl0A76A
Starting zookeeper
zookeeper is [UP]
Starting kafka
-Kafka failed to start
kafka is [DOWN]
```

Digging thru the `kafka.stdout` I see `Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9990`.  I can work around things by setting the full `KAFKA_JMX_OPTS`.

```bash
export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.port=9990"
```

Is there an easier way to set `JMX_PORT` scoped to the kafka broker only?

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/confluent-cli/pull/117
