### ISSUE TITLE
Is this repository deprecated? 

### ISSUE THREAD

**Issue by benesch** [confluentinc/confluent-cli#127]
This no longer seems to be the CLI that's distributed with Confluent Platform 5.3+. The new CLI is some Go binary, whose source is not available, that seems to embed a patched version of the shell script in this repository.

So what's the status of this CLI? Will it continue to be maintained as a standalone project? Or is it dead?

**Comment by DABH** [comment]
Hi @benesch , sorry for a much delayed reply.  Some of this has been answered in #133 , but, to provide a bit of additional info: we will keep this repository open at least as long as the old CLI is maintained (i.e. until Confluent Platform 5.2.x and earlier has its support discontinued, which is probably ~2 years from now).  And depending on whether it's more helpful or more confusing, we may continue to keep this repo around even after that.  As far as maintenance goes, we will hotfix urgent issues for older versions of Confluent Platform as needed, but we are only actively developing the new Go CLI, not this old bash CLI.
