### ISSUE TITLE
Confluent CLI can't support arm64

### ISSUE THREAD

**Issue by k36666** [confluentinc/confluent-cli#131]
How can I use Confluent on arm64?

**Comment by ewencp** [comment]
This is the repository for the deprecated bash CLI, but more generally Confluent Platform isn't supported on arm64 currently. However, we'll make a note of this -- we've seen a few other requests for this as well.

**Comment by ewencp** [comment]
Oh, I also meant to mention, in general you can find support and compatibility support [in our docs|https://docs.confluent.io/current/installation/versions-interoperability.html], though architecture support is not currently explicitly called out there. i386/amd64 are the currently supported architectures.
