### ISSUE TITLE
Filing issues for the new proprietary Confluent CLI

### ISSUE THREAD

**Issue by amotl** [confluentinc/confluent-cli#133]
Dear lovely people of Confluent,

first things first: Thanks for conceiving and maintaining the Confluent distribution. It saves us a tremendous amount of manual setup work, so please keep up the spirit!

Today, we found a problem with the new [Confluent CLI](https://docs.confluent.io/current/cli/) so we would like to humbly ask where to file respective issues for? Would this repository still be the right place?

> This repository is no longer maintained by Confluent. It has been superceded by the proprietary `confluent-cli` which provides significantly more functionality, including ACLs, RBAC, and Audit Log management for Confluent Platform.

@benesch also mentioned that within #127:
> This no longer seems to be the CLI that's distributed with Confluent Platform 5.3+. The new CLI is some Go binary, whose source is not available.

Will you even consider making its code open source again?

With kind regards,
Andreas.

**Comment by DABH** [comment]
Hi @amotl , thank you for the kind words and for reaching out!

If you have issues/bugs/requests with the new Confluent CLI, please feel free to file a support ticket if you are a Confluent customer (and it will get routed to us as appropriate), or check out the #confluent-cli channel in the Confluent Community Slack (which we also try to monitor).  As you and @benesch mentioned, this repo is for the old Confluent CLI which is no longer being worked on -- so we do not monitor issues in the repo too frequently, unfortunately.  However, we do have a goal to make the new CLI source available at some point in the future, so this is definitely on our long-term roadmap.  We'd definitely welcome feedback on how having the CLI be source available would be helpful to you or your team.

Thanks!

**Comment by amotl** [comment]
Dear David,

> We do have a goal to make the new CLI source available at some point in the future.

Great to hear!

> We'd definitely welcome feedback on how having the CLI be source available would be helpful to you or your team.

Being able to inspect the source code will encourage many people to contribute fixes and improvements. That is quite the same as with all other software components.

Beyond that, having a dedicated repository is a point where people can gather around the piece of software which more often than not will spawn fruitful discussions.

With kind regards,
Andreas.
