### ISSUE TITLE
Getting available versions S3 hangs on no connectivity

### ISSUE THREAD

**Issue by sionsmith** [confluentinc/confluent-cli#140]
Once installing CLI if the server does not have connectivity to S3 it hangs every time you run a commnad:

```
2021-04-13T10:36:24.403Z [DEBUG] Getting available versions from https://s3-us-west-2.amazonaws.com/confluent.cloud?prefix=confluent-cli/binaries/
2021-04-13T10:36:54.404Z [WARN]  unable to get available binary versions: Get "https://s3-us-west-2.amazonaws.com/confluent.cloud?prefix=confluent-cli/binaries/": dial tcp 52.218.196.232:443: i/o timeout
```

Is there a way to turn this off? Or can we add a flag to force `no_check_version` or something?

**Comment by DABH** [comment]
@sionsmith Try adding `"disable_update_check": true` to the top level of your CLI config file (`~/.confluent/config.json`).  If that doesn't work, you can also try `"disable_updates": true`, but I think just the first one should be sufficient.  Please feel free to re-open or file a support ticket if issues persist (support ticket will likely get faster response).

**Comment by cdia8890** [comment]
For anyone who comes here checking this for windows: the `config.json` file is available at `C:\Users\<your user name>\.confluent`. I experienced that all the confluent CLI commands were hanging and taking a long time to execute, which was resolved by putting the above configuration in place.
