### ISSUE TITLE
kafka-rest doesn't start if C3 monitoring interceptors are configured

### ISSUE THREAD

**Issue by hjespers** [confluentinc/confluent-cli#21]
The CLASSPATH  from the users shell is not being picked up so so any CPE components configured in kafka-rest or anywhere else are not resolved. For kafka-rest this leads to a failure to start.

**Comment by kkonstantine** [comment]
Per service environment variable overrides are supported with the appropriate prefix. 
For instance, to set the CLASSPATH to kafka-rest, one needs to set:
`KAFKAREST_CLASSPATH`. 

Similar to other services. Better documentation is required here.

Specifically, for monitoring interceptors, they are added by default after https://github.com/confluentinc/confluent-cli/pull/60 was added.
