### ISSUE TITLE
"confluent config" doesn't include custom jars required for third party connectors

### ISSUE THREAD

**Issue by hjespers** [confluentinc/confluent-cli#22]
I am unable to add a third party connector using "confluent config mqtt -d mqtt-config.json"  or "confluent load mqtt -d mqtt-config.json".

it appears to load but then does not start.

$ confluent config mqtt
Current configuration of 'mqtt' connector:
{
  "error_code": 404,
  "message": "Connector mqtt not found"
}

**Comment by kkonstantine** [comment]
Marking this as resolved, feel free to reopen if a case is missed from the explanation above.
