### ISSUE TITLE
top is broken in Linux

### ISSUE THREAD

**Issue by kkonstantine** [confluentinc/confluent-cli#42]
There's a stray comma that does not allow `top` to run on certain linux distros for all the services. 
Also a check for empty pid needs to be added.

**Comment by gwenshap** [comment]
👍

**Comment by vthot4** [comment]
I imagine that there will be better ways but I have solved with these lines:

top_pid=`echo $pids| sed 's/.$//g'`
top -p "$top_pid"

**Comment by kkonstantine** [comment]
Hi @vthot4, thanks so much for checking this out and suggesting a fix! 
Allow me to encourage you to go ahead and directly issue a PR next time you have a similar suggestion. All of us will be thrilled! :)

Since the above had a minor issue of not catching multiple commas (the original bug could produce `,,,,,` as well) I went ahead and issued a different patch which is also pretty brief. 

Feel free to check it out and even try it from here: https://github.com/confluentinc/confluent-cli/pull/45

**Comment by kkonstantine** [comment]
Fixed by: https://github.com/confluentinc/confluent-cli/pull/45
