### ISSUE TITLE
Cannot start Schema Registry, Kafka Server is not running. Check your deployment

### ISSUE THREAD

**Issue by pavankjadda** [confluentinc/confluent-cli#79]
Hello,
I just downloaded Confluent and try to run it [based on instructions](https://docs.confluent.io/current/installation/installing_cp.html). When I run the command `./confluent start`, I get an error message 
```
$ ./confluent start
zookeeper is already running. Try restarting if needed
Starting kafka
Kafka failed to start
kafka is [DOWN]
Cannot start Schema Registry, Kafka Server is not running. Check your deployment

```
Am I doing something wrong here?

**Comment by pavankjadda** [comment]
Never mind guys. Even though I stopped other Kafka service, it's still running in the background. After killing it manually, Kafka server is up

**Comment by mayankbharti26** [comment]
>>jps
>>kill -9 pid
